AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Manuel - Knowledge Base Phase 2

  Adds OpenSearch and Bedrock Knowledge Base to existing infrastructure

Parameters:
  Stage:
    Type: String
    Default: dev
    Description: Deployment stage

  ExistingManualsBucket:
    Type: String
    Description: Name of the existing S3 bucket for manuals

  EmbeddingModelId:
    Type: String
    Default: amazon.titan-embed-text-v2:0
    Description: Bedrock embedding model ID

  TextModelId:
    Type: String
    Default: eu.anthropic.claude-sonnet-4-20250514-v1:0
    Description: Bedrock text generation model ID

  UseInferenceProfile:
    Type: String
    Default: "true"
    AllowedValues: ["true", "false"]
    Description: Whether to use cross-region inference profiles

  KnowledgeBaseRetrievalResults:
    Type: Number
    Default: 3
    Description: Number of results to retrieve from Knowledge Base

Resources:
  # OpenSearch Serverless Security Policy (Must be first)
  OpenSearchSecurityPolicy:
    Type: AWS::OpenSearchServerless::SecurityPolicy
    Properties:
      Name: !Sub manuel-security-policy-v2-${Stage}
      Type: encryption
      Description: Security policy for Manuel OpenSearch collection
      Policy: !Sub |
        {
          "Rules": [
            {
              "ResourceType": "collection",
              "Resource": ["collection/manuel-vectors-v2-${Stage}"]
            }
          ],
          "AWSOwnedKey": true
        }

  # OpenSearch Network Policy
  OpenSearchNetworkPolicy:
    Type: AWS::OpenSearchServerless::SecurityPolicy
    Properties:
      Name: !Sub manuel-network-policy-v2-${Stage}
      Type: network
      Description: Network policy for Manuel OpenSearch collection
      Policy: !Sub |
        [
          {
            "Rules": [
              {
                "ResourceType": "collection",
                "Resource": ["collection/manuel-vectors-v2-${Stage}"]
              },
              {
                "ResourceType": "dashboard",
                "Resource": ["collection/manuel-vectors-v2-${Stage}"]
              }
            ],
            "AllowFromPublic": true
          }
        ]

  # OpenSearch Serverless Collection for Vector Storage
  OpenSearchCollection:
    Type: AWS::OpenSearchServerless::Collection
    DependsOn:
      - OpenSearchSecurityPolicy
      - OpenSearchNetworkPolicy
    Properties:
      Name: !Sub manuel-vectors-v2-${Stage}
      Type: VECTORSEARCH
      Description: Vector storage for Manuel knowledge base
      Tags:
        - Key: Project
          Value: Manuel
        - Key: Environment
          Value: !Ref Stage

  # IAM Role for Bedrock Knowledge Base
  BedrockKnowledgeBaseRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub manuel-bedrock-kb-role-v2-${Stage}
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: bedrock.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonBedrockFullAccess
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:ListBucket
                Resource:
                  - !Sub "arn:aws:s3:::${ExistingManualsBucket}"
                  - !Sub "arn:aws:s3:::${ExistingManualsBucket}/*"
        - PolicyName: OpenSearchAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - aoss:APIAccessAll
                Resource: !GetAtt OpenSearchCollection.Arn

  # OpenSearch Serverless Access Policy (Must reference the role)
  OpenSearchAccessPolicy:
    Type: AWS::OpenSearchServerless::AccessPolicy
    DependsOn: BedrockKnowledgeBaseRole
    Properties:
      Name: !Sub manuel-access-policy-v2-${Stage}
      Type: data
      Description: Access policy for Manuel OpenSearch collection
      Policy: !Sub |
        [
          {
            "Rules": [
              {
                "ResourceType": "index",
                "Resource": ["index/manuel-vectors-v2-${Stage}/*"],
                "Permission": ["aoss:*"]
              },
              {
                "ResourceType": "collection",
                "Resource": ["collection/manuel-vectors-v2-${Stage}"],
                "Permission": ["aoss:*"]
              }
            ],
            "Principal": ["${BedrockKnowledgeBaseRole.Arn}"]
          }
        ]

  # Bedrock Knowledge Base
  BedrockKnowledgeBase:
    Type: AWS::Bedrock::KnowledgeBase
    DependsOn: OpenSearchAccessPolicy
    Properties:
      Name: !Sub manuel-knowledge-base-v2-${Stage}
      Description: Knowledge base for Manuel product manuals with user isolation
      RoleArn: !GetAtt BedrockKnowledgeBaseRole.Arn
      KnowledgeBaseConfiguration:
        Type: VECTOR
        VectorKnowledgeBaseConfiguration:
          EmbeddingModelArn: !Sub arn:aws:bedrock:${AWS::Region}::foundation-model/${EmbeddingModelId}
      StorageConfiguration:
        Type: OPENSEARCH_SERVERLESS
        OpensearchServerlessConfiguration:
          CollectionArn: !GetAtt OpenSearchCollection.Arn
          VectorIndexName: bedrock-knowledge-base-default-index
          FieldMapping:
            VectorField: bedrock-knowledge-base-default-vector
            TextField: bedrock-knowledge-base-text-field
            MetadataField: bedrock-knowledge-base-metadata-field
      Tags:
        Project: Manuel
        Environment: !Ref Stage

  # Data Source for Knowledge Base
  BedrockDataSource:
    Type: AWS::Bedrock::DataSource
    Properties:
      KnowledgeBaseId: !Ref BedrockKnowledgeBase
      Name: !Sub manuel-manuals-source-v2-${Stage}
      Description: S3 data source for product manuals with user metadata
      DataSourceConfiguration:
        Type: S3
        S3Configuration:
          BucketArn: !Sub "arn:aws:s3:::${ExistingManualsBucket}"
          InclusionPrefixes:
            - manuals/

Outputs:
  KnowledgeBaseId:
    Description: Bedrock Knowledge Base ID
    Value: !Ref BedrockKnowledgeBase
    Export:
      Name: !Sub "${AWS::StackName}-KnowledgeBaseId"

  OpenSearchCollectionEndpoint:
    Description: OpenSearch Collection Endpoint
    Value: !GetAtt OpenSearchCollection.CollectionEndpoint
    Export:
      Name: !Sub "${AWS::StackName}-OpenSearchEndpoint"

  OpenSearchCollectionArn:
    Description: OpenSearch Collection ARN
    Value: !GetAtt OpenSearchCollection.Arn
    Export:
      Name: !Sub "${AWS::StackName}-OpenSearchArn"
